### ISSUE TITLE
Add-on ds18b20-webthing

### ISSUE THREAD

**Issue by pthelm** [blackfyre/ds18b20-webthing#1]
Hi
I am very interested in using the ds18b20 connected to a Raspberry-pi as part of the Mozilla IOT webthings. I am new to Mozilla IOT and a novice with Raspberry-pi and would like to use the ds18b20 which is connected to the GPIO of the Raspberry-Pi as a IOT webthing. Is your "ds18b20-webthing" able to be used in this way? If so how do I add-on or use as a webthing?
Thanks Peter

**Comment by blackfyre** [comment]
@pthelm 
Thank you for your interest, however this library was written for an ESP8266 or compatible (ESP32, Arduino,...) micro controller.
For an on-board solution I'd recommend the Mozilla Gateway forum at https://discourse.mozilla.org/c/iot

**Comment by pthelm** [comment]
Hi Meki

Thanks for your reply.

Since I asked the question I have purchased a ESP8266 and am about to try out your code.

My project is a swimming pool solar controller and using remote temperature sensors makes more sense for my application.

Thanks again

Peter

**Comment by pthelm** [comment]
Hi Meki,

I hope you may be able to offer some advice regarding your code for a DS18b20 temp sensor connected to a ESP8266.

I have now tried running the code and when I try to connect to the programmed ESP8266 via my Mozilla IOT the ESP8266 continually resets.

 

When I received the ESP8266 I successfully tested it as a standalone server with a  DS18b20 temp sensor and was able to connect via http://nnn.nnn.nnn.nnn so I have confirmed basic operation.

 

Has your code been tested?

Im I correct in assuming you connect to the ESP8266 as a webthing via the URL http://nnn.nnn.nnn.nnn/things/weather?

 

Thanks for your help

Best Regards Peter

 

 

 

From: Peter Helm [mailto:petehelm@tpg.com.au] 
Sent: Monday, 24 December 2018 7:33 PM
To: 'blackfyre/ds18b20-webthing' <reply@reply.github.com>
Subject: RE: [blackfyre/ds18b20-webthing] Add-on ds18b20-webthing (#1)

 

Hi Meki

Thanks for your reply.

Since I asked the question I have purchased a ESP8266 and am about to try out your code.

My project is a swimming pool solar controller and using remote temperature sensors makes more sense for my application.

Thanks again

Peter
